DROP TABLE IF EXISTS playlist_musicas;
DROP TABLE IF EXISTS playlists;

CREATE TABLE playlists (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao VARCHAR(255)
);

CREATE TABLE playlist_musicas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid INT NOT NULL,
    musicaid INT NOT NULL,
    FOREIGN KEY (playlistid) REFERENCES playlists(id)
);

INSERT INTO playlists (nome, descricao)
VALUES ('Clássicos do Rock', 'Grandes clássicos do rock internacional');

INSERT INTO playlists (nome, descricao)
VALUES ('Música Brasileira', 'Clássicos da música brasileira');

INSERT INTO playlists (nome, descricao)
VALUES ('Pop Internacional', 'Sucessos do pop internacional');

INSERT INTO playlists (nome, descricao)
VALUES ('Para Relaxar', 'Músicas para momentos tranquilos');

INSERT INTO playlists (nome, descricao)
VALUES ('Favoritas', 'Minha seleção pessoal de músicas favoritas');

INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (1, 1);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (1, 3);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (1, 5);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (2, 4);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (3, 2);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (4, 1);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (4, 4);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (5, 1);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (5, 2);
INSERT INTO playlist_musicas (playlistid, musicaid) VALUES (5, 5);
