DROP TABLE IF EXISTS musicas;

CREATE TABLE musicas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo VARCHAR(150) NOT NULL,
    artista VARCHAR(150) NOT NULL,
    album VARCHAR(150),
    duracao INTEGER NOT NULL,
    genero VARCHAR(50)
);

INSERT INTO musicas (titulo, artista, album, duracao, genero)
VALUES ('Imagine', 'John Lennon', 'Imagine', 183, 'Rock');

INSERT INTO musicas (titulo, artista, album, duracao, genero)
VALUES ('Billie Jean', 'Michael Jackson', 'Thriller', 294, 'Pop');

INSERT INTO musicas (titulo, artista, album, duracao, genero)
VALUES ('Bohemian Rhapsody', 'Queen', 'A Night at the Opera', 354, 'Rock');

INSERT INTO musicas (titulo, artista, album, duracao, genero)
VALUES ('Garota de Ipanema', 'Tom Jobim', 'Getz/Gilberto', 328, 'Bossa Nova');

INSERT INTO musicas (titulo, artista, album, duracao, genero)
VALUES ('Tempo Perdido', 'Legião Urbana', 'Dois', 301, 'Rock');
