DROP TABLE IF EXISTS reproducoes;

CREATE TABLE reproducoes (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlistid INT NOT NULL,
    datahora TIMESTAMP NOT NULL
);

INSERT INTO reproducoes (playlistid, datahora) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (1, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (2, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (2, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (2, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (3, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (3, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (4, CURRENT_TIMESTAMP);
INSERT INTO reproducoes (playlistid, datahora) VALUES (5, CURRENT_TIMESTAMP);
